### ISSUE TITLE
Game crashes on loading screen

### ISSUE THREAD

**Issue by XxRabyPower00xX** [Ladysnake/Illuminations#31] opened 2020-07-23 23:49 UTC
I have no idea why, maybe it's incompatible with sodium, I don't know, here's some logs:
[2020-07-24-1.log.gz](https://github.com/Ladysnake/Illuminations/files/4969605/2020-07-24-1.log.gz)
[2020-07-24-2.log.gz](https://github.com/Ladysnake/Illuminations/files/4969606/2020-07-24-2.log.gz)

**Comment by Pyrofab** [comment] 2020-07-23 23:49
Duplicate of #30

**Closed by Pyrofab** 2020-07-23 23:49 UTC
