### ISSUE TITLE
Game crashes when going too far on modded server

### ISSUE THREAD

**Issue by Berkouli** [Ladysnake/Illuminations#142] opened 2022-06-23 19:04 UTC
It was working fine until the latest update

java.lang.NullPointerException: Cannot invoke "com.google.common.collect.ImmutableSet.iterator()" because "illuminationDataSet" is null
at net.minecraft.client.world.ClientWorld.spawnParticles (ClientWorld:4152)
at net.minecraft.client.world.ClientWorld.handler$dnb000$randomBlockDisplayTick (ClientWorld:4136)
at net.minecraft.client.world.ClientWorld.randomBlockDisplayTick (ClientWorld:403)
at net.minecraft.client.world.ClientWorld.doRandomBlockDisplayTicks (ClientWorld:358)
at net.minecraft.client.MinecraftClient.tick (MinecraftClient:1854)
at net.minecraft.client.MinecraftClient.render (MinecraftClient:1101)
at net.minecraft.client.MinecraftClient.run (MinecraftClient:734)
at net.minecraft.client.main.Main.main (Main:237)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch (MinecraftGameProvider.java:461)
at net.fabricmc.loader.impl.launch.knot.Knot.launch (Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main (KnotClient.java:23)

**Comment by aAndrew3030** [comment] 2022-06-23 22:24
Having the same issue, log
[latest.log](https://github.com/Ladysnake/Illuminations/files/8971737/latest.log)

**Comment by doctor4t** [comment] 2022-06-24 08:10
Duplicate of #141

**Closed by doctor4t** 2022-06-24 08:10 UTC
Labels: invalid
