### ISSUE TITLE
Crashes with Sodium for 1.17

### ISSUE THREAD

**Issue by AViewFromTheTop** [Ladysnake/Illuminations#86] opened 2021-07-09 00:09 UTC
When I tried to play with Sodium, the game would crash while booting. After I removed Sodium from my mods folder, the game worked just fine.
Log: https://paste.ee/p/bbwhn
Edit: I was also using Iris, but the game worked just fine for me with Iris and Illuminations together. It seems to only be Sodium causing the issue (both the Iris Compatibility fork and the normal version)

**Comment by wolfstriker134** [comment] 2021-07-09 04:35
yup

**Comment by ttltrashmammal** [comment] 2021-07-09 05:21
Commented in the Discord about this as it happened to me earlier and was told to make a post (just saw the message though ^^') and came across this. Using Iris 1.1.0, it crashes immediately with this error log 
[latest.log](https://github.com/Ladysnake/Illuminations/files/6788878/latest.log)
, however I cannot find the announcement for 1.1.0 on their Github, just on their Discord. A partial port of Sodium was added to Iris to make it workable for 1.1.0:
From the Iris Discord:
![Screenshot_58](https://user-images.githubusercontent.com/86491611/125026739-d1621580-e04a-11eb-8f68-539d0ea6e36f.png)
As far as I know (and it was confirmed), Illuminations has had issues working with Sodium in the past, so with Iris having a fork of Sodium in it, it makes sense. Jellysquid is still in process of working on the full version of 1.17 so the file could change, but the Iris official release can be downloaded on their site. 
(I know most of this is easily Google-able but it's all of the information I put in the Discord.)

I originally thought it was just Iris as it's had an issue or two with me already, but turns out it was Sodium.

**Comment by wolfstriker134** [comment] 2021-07-09 05:23
cool. thanks you for letting us know!

**Comment by wolfstriker134** [comment] 2021-07-12 06:10
Do you have any idea of when this will be fixed?

**Comment by ttltrashmammal** [comment] 2021-07-12 06:19
To be fair, Sodium isn't even fully released yet. The Iris/Sodium team are currently working on a new update themselves due to some *serious* memory leak issues (to the point my computer drops to 1 fps after a few hours of playing, when I can run three different mods twice as extensive as it at the same time with no issue) that they're currently addressing. That update could break any upcoming update put out for this as well; especially if the issue is deeper in Sodium's code itself. I would personally wait and see what the Iris/Sodium team decides to do and if we hear about a time frame in the next day or so.

**Comment by wolfstriker134** [comment] 2021-07-12 07:38
ok thank you

**Comment by doctor4t** [comment] 2021-07-12 08:35
Forgot to close, but this was fixed in 1.6, released 14 hours ago.

**Closed by doctor4t** 2021-07-12 08:35 UTC
Labels: bug
